name: Manual Run
on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull Request Number'
        required: false

jobs:
  build_eas_local:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Get PR SHA
        run: | 
          echo PR_SHA=$(curl --location --request GET 'https://api.github.com/repos/yogeshpanchal8195/dispatcher-demo/pulls/1' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.PAT_TOKEN }}' | jq .head.sha) >> $GITHUB_ENV

      - run: echo ${{env.PR_SHA}}

      - run: echo ${{ github.event.inputs.pull_request_number }}
      - run: echo ${{env.PR_SHA}}
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          ref: ${{env.PR_SHA}}
      