name: Repo Testing

# only trigger on pull request closed events
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - run: |
          curl -L -X POST 'https://api.github.com/repos/yogeshpanchal8195/receiver-demo/dispatches' \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer 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' \
          -d '{
              "event_type":"automate-test"
              "client_payload":{"url":"alpha"}
          }'
      # - name: Repository Dispatch 
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.PAT_TOKEN }}
      #     repository: yogeshpanchal8195/receiver-demo
      #     event-type: my-event 
      #     client-payload: '{"head_ref": "${{ github.head_ref }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "url": "https://expo.dev/artifacts/eas/3U9hD3WPuycnoB5kj9jMdV.apk"}'
