name: Workflow Testing

# only trigger on pull request closed events
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: yogeshpanchal8195
          repo: receiver-demo
          github_token: ${{ secrets.PAT_TOKEN }}
          github_user: yogeshpanchal8195
          workflow_file_name: workflow.yml
          ref: main
          wait_interval: 10
          client_payload: '{
            "url": "https://expo.dev/artifacts/eas/3U9hD3WPuycnoB5kj9jMdV.apk"
          }'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true