name: Workflow Testing

# only trigger on pull request closed events
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: workflow
          repo: yogeshpanchal8195/receiver-demo
          token: ${{ secrets.PAT_TOKEN }}
          inputs: '{ "message": "blah blah", "debug": true }'

      